services:
  node-app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./app:/app
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - ./app/config.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./app/config.env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
