services:
  node-app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    command: npm run dev
    ports:
      - '3000:3000'
    env_file:
      - ./config.env
  mongo:
    image: mongo
    env_file:
      - ./config.env