services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    command: npm run dev
    ports:
      - '3000:3000'
    env_file:
      - ./config.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./config.env
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: