services:
  node-app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - '3000:3000'
    env_file:
      - ./config.env
