services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./app:/app
    command: npm run dev
    env_file:
      - ./app/config.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./app/config.env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
